

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Execute the unit tests
        run: npm run test:unit

  ui-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install
      - name: Istall Playwright
        run: npx playwright install 
        

      - name: Execute the UI tests
        run: npm run test:ui