

name: Build and Test

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou the code
        uses: actions/checkout@v4
      - name: Use Node.js 20x
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install npm dependencies 
      - run: npm install
      - name: Executhe the unit tests
      - run: npm run test:unit


